// <auto-generated />
using System;
using BaseHousingOps.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseHousingOps.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("PersonSequence");

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.Lease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_leases");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_leases_unit_id");

                    b.ToTable("leases", (string)null);
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ResidentId")
                        .HasColumnType("integer")
                        .HasColumnName("resident_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<string>("Urgency")
                        .HasColumnType("text")
                        .HasColumnName("urgency");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_requests");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("ix_maintenance_requests_resident_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_maintenance_requests_unit_id");

                    b.ToTable("maintenance_requests", (string)null);
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"PersonSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bedrooms");

                    b.Property<bool>("IsVacant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vacant");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_number");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_units_property_id");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date")
                        .HasColumnName("completed_date");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("integer")
                        .HasColumnName("technician_id");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_work_orders_request_id");

                    b.HasIndex("TechnicianId")
                        .HasDatabaseName("ix_work_orders_technician_id");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.Resident", b =>
                {
                    b.HasBaseType("BaseHousingOps.Domain.Entities.Person");

                    b.Property<string>("BranchOfService")
                        .HasColumnType("text")
                        .HasColumnName("branch_of_service");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.Technician", b =>
                {
                    b.HasBaseType("BaseHousingOps.Domain.Entities.Person");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialty");

                    b.ToTable("technicians", (string)null);
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.Lease", b =>
                {
                    b.HasOne("BaseHousingOps.Domain.Entities.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leases_units_unit_id");

                    b.OwnsMany("BaseHousingOps.Domain.Entities.LeaseResident", "Residents", b1 =>
                        {
                            b1.Property<int>("LeaseId")
                                .HasColumnType("integer")
                                .HasColumnName("lease_id");

                            b1.Property<int>("ResidentId")
                                .HasColumnType("integer")
                                .HasColumnName("resident_id");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("role");

                            b1.HasKey("LeaseId", "ResidentId")
                                .HasName("pk_lease_resident");

                            b1.HasIndex("ResidentId")
                                .HasDatabaseName("ix_lease_resident_resident_id");

                            b1.ToTable("lease_resident", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeaseId")
                                .HasConstraintName("fk_lease_resident_leases_lease_id");

                            b1.HasOne("BaseHousingOps.Domain.Entities.Resident", null)
                                .WithMany()
                                .HasForeignKey("ResidentId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_lease_resident_residents_resident_id");
                        });

                    b.Navigation("Residents");
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("BaseHousingOps.Domain.Entities.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_residents_resident_id");

                    b.HasOne("BaseHousingOps.Domain.Entities.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_units_unit_id");
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.Unit", b =>
                {
                    b.HasOne("BaseHousingOps.Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_units_properties_property_id");
                });

            modelBuilder.Entity("BaseHousingOps.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("BaseHousingOps.Domain.Entities.MaintenanceRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_maintenance_requests_request_id");

                    b.HasOne("BaseHousingOps.Domain.Entities.Technician", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_orders_technicians_technician_id");
                });
#pragma warning restore 612, 618
        }
    }
}
